import os
import pandas as pd
import numpy as np
from datetime import timedelta

# Match your existing project path structure
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "data", "trades_scaled.csv")
RAW_DIR = os.path.join(BASE_DIR, "data", "raw_dataset")

def retroactive_audit():
    if not os.path.exists(CSV_PATH):
        print(f"[!] Error: {CSV_PATH} not found.")
        return

    df = pd.read_csv(CSV_PATH)
    
    print("="*60)
    print(" 🔎 RETROACTIVE 2R / 8-EMA AUDIT INITIATED 🔎")
    print("="*60)
    print(f"Auditing {len(df)} historical trades using local data...\n")

    changed_outcomes = 0

    # Ensure compatibility with your updated CSV format
    date_col = 'Entry_Time' if 'Entry_Time' in df.columns else 'Date'

    for index, row in df.iterrows():
        ticker = row['Ticker']
        trade_id = row['Trade_ID']
        original_outcome = str(row['Outcome']).strip().capitalize()
        
        trade_datetime = pd.to_datetime(row[date_col])
        trade_date = trade_datetime.date()
        
        try:
            # 1. Point directly to the daily.csv generated by your download script
            trade_dir = os.path.join(RAW_DIR, str(trade_id))
            daily_path = os.path.join(trade_dir, "daily.csv")
            
            if not os.path.exists(daily_path):
                print(f"[!] Local data not found for {trade_id} at {daily_path}. Skipping.")
                continue
                
            # 2. Read the standardized local CSV
            ticker_data = pd.read_csv(daily_path, index_col='date', parse_dates=True)
            ticker_data.index = ticker_data.index.tz_localize(None)

            # 3. Calculate 8 EMA using the 'close' column
            ticker_data['8ema'] = ticker_data['close'].ewm(span=8, adjust=False).mean()

            # 4. Isolate the dates
            trade_ts = pd.Timestamp(trade_date)
            if trade_ts not in ticker_data.index:
                print(f"[!] Trade date {trade_date} not found in {ticker} local data.")
                continue
                
            entry_day_data = ticker_data.loc[trade_ts]
            pre_breakout_data = ticker_data.loc[:trade_ts - timedelta(days=1)]
            
            if len(pre_breakout_data) < 20:
                print(f"[!] Not enough historical local data for {ticker} prior to {trade_date}.")
                continue
                
            # Calculate Risk Metrics
            entry_price = pre_breakout_data['high'].iloc[-20:].max()
            entry_8ema = entry_day_data['8ema']
            
            risk = entry_price - entry_8ema
            
            if risk <= 0:
                mechanical_outcome = 'Loss'
                reason = "Invalid Risk (8EMA > Entry)"
            else:
                initial_stop = entry_8ema
                target_1r = entry_price + risk
                target_2r = entry_price + (risk * 2)
                
                post_breakout_data = ticker_data.loc[trade_ts + timedelta(days=1):]
                
                current_stop = initial_stop
                mechanical_outcome = "Pending"
                reason = "Trade still active based on available data."
                
                # Run the simulation forward
                for sim_date, sim_row in post_breakout_data.iterrows():
                    high = sim_row['high']
                    low = sim_row['low']
                    
                    if low <= current_stop:
                        mechanical_outcome = "Loss"
                        if current_stop == entry_price:
                            reason = f"Stopped at Breakeven on {sim_date.date()}"
                        else:
                            reason = f"Stopped at Initial Risk on {sim_date.date()}"
                        break
                        
                    if high >= target_2r:
                        mechanical_outcome = "Win"
                        reason = f"Hit strict 2R Target on {sim_date.date()}"
                        break
                        
                    if high >= target_1r and current_stop == initial_stop:
                        current_stop = entry_price

            # Print if the script changes your original label
            if mechanical_outcome != "Pending" and mechanical_outcome != original_outcome:
                print(f"⚠️ OUTCOME FLIPPED: {trade_id}")
                print(f"   Original: {original_outcome} | Mechanical: {mechanical_outcome}")
                print(f"   Reason: {reason}")
                print("-" * 50)
                changed_outcomes += 1

            # Update the dataframe
            if mechanical_outcome != "Pending":
                df.at[index, 'Outcome'] = mechanical_outcome

        except Exception as e:
            print(f"[!] Error simulating {trade_id}: {e}")

    # Save over the original CSV
    df.to_csv(CSV_PATH, index=False)
    print("\n" + "="*60)
    print(f"[+] Audit complete. {changed_outcomes} historical trades were reclassified.")
    print(f"[+] {CSV_PATH} has been overwritten with strict mechanical outcomes.")
    print("="*60)

if __name__ == "__main__":
    retroactive_audit()